load("@//bazel:build_settings.bzl", "common_build_setting")

common_build_setting(
    name = "compiler_name",
    build_setting_default = "auto",
)

common_build_setting(
    name = "arch",
    build_setting_default = "auto",
)
