load("//bazel:cpp_rules.bzl", "cpp_module")

# cc_library(
#     name = "foo_headers",
#     hdrs = ["foo.hpp"],
# )

cpp_module(
    name = "foo",
    srcs = ["foo.cpp"],
    hdrs = ["foo.hpp"]
    # deps = [":foo_headers"],
)

# cpp_module(
#     name = "proj",
#     srcs = ["main.cpp"],
#     deps = [":foo"],
# )
